
# file that will be runned by default if no file is passed on the run command
run = "tests/main.py" # list[str] | str
prepare = false # decides if file at run should be prepared (has PyCS code) or not; this may break imports

[ModuleImport]

# "package" module name
name = "tests/origin"

# file which will import module
modules = [
  
  # modules that package modulewill import
  "tests/funcs.py",
]

# if true then: from module import *
# if false: import module 
import_all = true



